name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  packages: write


jobs:
  tests:
    name: Run Python Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest
      - name: Run tests
        run: |
          PYTHONPATH=. pytest
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@7006c4492b2e0ee0f816d36501671557c97f5995 # v8.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: [tests, sonarqube]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Build Docker image
        run: |
          docker build -t ghcr.io/catenaliggette/testtrivyproject:latest .


      - name: Scan Docker image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/catenaliggette/testtrivyproject:latest
          format: table
          severity: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
          exit-code: 0


      - name: Scan Docker configuration
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: config
          scan-ref: .
          severity: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
          exit-code: 0


      - name: Run Docker container
        run: |
          docker run -d \
          -p 5000:5000 \
          --name test-container \
          ghcr.io/catenaliggette/testtrivyproject:latest


      - name: Test running container
        run: |
          sleep 5
          curl --fail http://localhost:5000


      - name: Stop container
        run: |
          docker stop test-container


      - name: Push Docker image
        run: |
          docker push ghcr.io/catenaliggette/testtrivyproject:latest